namespace Motorola.Snapi.Constants.Enums
{
    public enum BeepPattern
    {
        OneHighShort,
        TwoHighShort,
        ThreeHighShort,
        FourHighShort,
        FiveHighShort,
        OneLowShort,
        TwoLowShort,
        ThreeLowShort,
        FourLowShort,
        FiveLowShort,
        OneHighLong,
        TwoHighLong,
        ThreeHighLong,
        FourHighLong,
        FiveHighLong,
        OneLowLong,
        TwoLowLong,
        ThreeLowLong,
        FourLowLong,
        FiveLowLong,
        FastWarble,
        SlowWarble,
        HighLow,
        LowHigh,
        HighLowHigh,
        LowHighLow,
        HighHighLowLow,
    }
}