/*Copyright (c) 2015 Fortelinea
/
/See the file license.txt for copying permission
*/

using Motorola.Snapi.Constants.Enums;

namespace Motorola.Snapi.EventArguments
{
    /// <summary>
    /// Contains the data generated by scanning a barcode.
    /// </summary>
    public class BarcodeScanEventArgs : ScannerEventArgs
    {

        /// <summary>
        /// Creates a new BarcodeScanEventArgs instance
        /// </summary>
        /// <param name="scannerId">Id number of the scanner triggering the event.</param>
        /// <param name="barcodeType">Symbology of the barcode that was scanned.</param>
        /// <param name="data">Decoded barcode string.</param>
        /// <param name="rawData">Decoded barcode string with headers.</param>
        public BarcodeScanEventArgs(uint scannerId, BarcodeType barcodeType, string data, byte[] rawData) : base(scannerId)
        {
            Data = data;
            RawData = rawData;
            BarcodeType = barcodeType;
        }

        /// <summary>
        /// Symbology of the barcode that was scanned.
        /// </summary>
        public BarcodeType BarcodeType { get; private set; }

        /// <summary>
        /// Decoded barcode string.
        /// </summary>
        public string Data { get; private set; }

        /// <summary>
        /// Decoded barcode string with headers.
        /// </summary>
        public byte[] RawData { get; private set; }
    }
}